### ISSUE TITLE
Do not require users to load JS first

### ISSUE THREAD

**Issue by savingschampion** [asaglimbeni/django-datetime-widget#61]
Use something like the following to defer execution of your plugin code, until Jquery is available.

```
function defer(method) {
    if (window.$)
        method();
    else
        setTimeout(function() { defer(method) }, 50);
}
```

**Comment by asaglimbeni** [comment]
Why do you need this ? 
It is enough to put the code in jquery ready method. Could you explain better your use case?
Thank you

**Comment by savingschampion** [comment]
Your form widget initializes your plugin inline in the DOM, via a like akin to 
```
$('input_id').datepicker()
```

This is an issue as we are loading all JS, including Jquery, at the bottom of the page.

With the above alteration, you can allow the form to initialize without requiring Jquery being loaded at the top of the page.

**Comment by bardo** [comment]
Same issue here, a fix would be great!
@savingschampion why not creating a quick pull request to speed things up? :)

**Comment by asaglimbeni** [comment]
I'm working to fix this issue! I hope to push the new version for the end of the week.
Thank you guys for your support and your reports.

**Comment by melwil** [comment]
Glad to see this has already been brought up, having the same issue!

**Comment by melwil** [comment]
Actually, this problem goes a bit deeper than jQuery alone, I also need put this inside the javascript loading in the bottom of the page: {{ form.media.js }}

Right now it needs to be declared before the form is printed, or I get the following error:

`Uncaught TypeError: undefined is not a function(index):268 (anonymous function)`

**Comment by asaglimbeni** [comment]
Hi Guys,
I pushed the fix to the develop branch, could you install it and confirm me that it works properly?
If everything goes well I can deploy a new version of the package to pypi.

**Comment by melwil** [comment]
bcec8a2aace2be761efbf5cfb8bac69ac55e5615 solves both problems presented in this issue; jQuery as well as the other js for this widget.

**Comment by savingschampion** [comment]
I am unable to test it at this time, we're currently doing QA for an upcoming release which is taking all my time at the moment.

**Comment by melwil** [comment]
@savingschampion Kind prod here, I'm just waiting for a new version of this to get one of my branches into testing :-)

**Comment by savingschampion** [comment]
No dice. I get the error that $ is not defined, because Jquery is being loaded at the bottom of the body.

```
<div id="id_alert_datetime" class="input-group date"><input class="datetimewidget form-control" id="id_alert_datetime" name="alert_datetime" readonly="" type="text" /> <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span><span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span></div>
<script type="text/javascript">
   $(function() {
       $("#id_alert_datetime").datetimepicker({format: 'dd/mm/yyyy hh:ii',
           pickerPosition: 'bottom-left',
           autoclose: true}).find('input').addClass("form-control");
   });
</script>
```

You can't use $() to wait for jQuery to load because jQuery itself defines $, which hasn't loaded yet.

A bit of a chicken and the egg problem. To solve it you need to use vanilla JS to wait for the $ variable to become defined.

You probably want to try something more like the following.

```
function init_date_picker(){
       $("#id_alert_datetime").datetimepicker({format: 'dd/mm/yyyy hh:ii',
       pickerPosition: 'bottom-left',
       autoclose: true}).find('input').addClass("form-control");
}

function wait_for_jquery() {
    if (window.$){
        //possibly some other JQuery checks to make sure that everything is loaded here
        init_date_picker();
    } else {
        setTimeout(wait_for_jquery, 50);
    }
}
wait_for_jquery();
```

**Comment by melwil** [comment]
Can't this be fixed by putting all the javascript in the form.media? That way you can put it wherever you want it, and make sure the ordering is not a problem.

**Comment by siolag161** [comment]
I was trying to fix this in here #72. Personally I move all the `js` code out of python, admittedly it's not DRY though ( two places for `input_format` for example`)

**Comment by sokser** [comment]
Same issue here.

**Comment by tylerecouture** [comment]
Just giving this widget a try and looks awesome so far, thank you!  However, it would be really nice to have this fix!

**Comment by strix** [comment]
I would also benefit from this fix (although it has been 10 months since the issue was submitted and I'm starting to lose hope).

**Comment by rafaelverger** [comment]
@asaglimbeni I thought it was fixed already... why it wasn't pushed to pypi?

**Comment by Atorich** [comment]
It still uses jquery in HTML in the form (even upstream from master). So it is not fixed, yep?

**Comment by joejean** [comment]
I'm still facing this issue. Any fixes (even temporary) please?

**Comment by rafaelverger** [comment]
@joejean get the code from @siolag161 fork: https://github.com/siolag161/django-datetime-widget
He opened a PR (#72) to here but wasn't merged till now...

**Comment by joejean** [comment]
Thanks @rafaelverger

**Comment by ssokolow** [comment]
What you really want is to do all your JS in an external file with the site-specific stuff in `data-` attributes.

That way, the site developer has the option of setting a Content Security Policy which instructs the browser to disallow inline JavaScript entirely to limit the potential for XSS. (jQuery itself requires inline CSS, which can also be a vector in some circumstances).

**Comment by ScottEAdams** [comment]
@ssokolow the above pull request does exactly that.

**Comment by ScottEAdams** [comment]
If all you need is a datepicker (without time functionality)  I created https://github.com/RDXT/django-bootstrap3-datepicker which uses only data attributes with https://github.com/uxsolutions/bootstrap-datepicker
